experimentName: test gcn rnn params using grid search
searchSpaceFile: .\tuning\nni\grid_search\search_space.json
trialCommand: python gcn_try.py --nni
trialCodeDirectory: .
trialConcurrency: 6
trialGpuNumber: 1
maxExperimentDuration: 24h
tuner:
  name: GridSearch
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 3