experimentName: test gcn rnn params using random tuner
searchSpaceFile: search_space.json
trialCommand: python run_gcn_rnn_trial.py --nni --seed 1 --data-folder-name reality_mining --data-name reality_mining_daily
trialCodeDirectory: ../../../..
trialConcurrency: 20
trialGpuNumber: 1
maxExperimentDuration: 24h
tuner:
  name: Random
    
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 5
