experimentName: test gcn rnn params using tpe tuner
searchSpaceFile: search_space.json
trialCommand: python run_gcn_rnn_trial.py --nni --seed 1 --data-folder-name reality_mining --data-name reality_mining_daily
trialCodeDirectory: ../../../..
trialConcurrency: 20
trialGpuNumber: 1
maxExperimentDuration: 24h
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 6
