experimentName: test gcn rnn params using tpe tuner
searchSpaceFile: .\tuning\nni\tpe\search_space.json
trialCommand: python gcn_try.py --nni
trialCodeDirectory: .
trialConcurrency: 6
trialGpuNumber: 1
maxExperimentDuration: 24h
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: True
  maxTrialNumberPerGpu: 3